spring:
  docker:
    compose:
      enabled: true
      file: collegeApp/docker-compose.yml
  datasource:
    url: jdbc:mysql://localhost:3306/collegeApp
    username: admin
    password: password@123
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    enabled: true
  openapi:
    info:
      title: College Management Application
      description: To manage college students, courses, and faculty.
      version: 1.0.0